tasks:
- init: source ./setup.sh
  command: |
        if [ -z ${ADYEN_HMAC_KEY+x} ] || [[ -z ${ADYEN_BALANCE_PLATFORM+x} ]]; then
            echo "Expected environment variables not found. Please set the ADYEN_HMAC_KEY and ADYEN_MERCHANT_ACCOUNT environment variables and rerun session https://gitpod.io/variables."
        else
            ./start.sh
        fi

# exposed ports
ports:
- name: Web App
  port: 8080
  onOpen: open-preview
  visibility: public

vscode:
  extensions:
    - ms-python.python
